service: docker-golang

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws

plugins:
  - serverless-offline

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    runtime: go1.x
    handler: bin/hello
    events:
      - http: GET hello
  world:
    runtime: go1.x
    handler: bin/world
    events:
      - http: GET world